// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Name  string `gorm:"column:name;not null;comment:姓名" json:"name"`                  // 姓名
	Phone string `gorm:"column:phone;not null;comment:号码" json:"phone"`                // 号码
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
